### ISSUE TITLE
Application does not send register bits for I11, I13, I14, I23 on 24 pin pals

### ISSUE THREAD

**Issue by raymondh2** [DuPAL-PAL-DUmper/DuPAL_Peeper#2] opened 2022-09-09 20:01 UTC
![11](https://user-images.githubusercontent.com/10180760/189433586-0951436a-ebe3-4278-bf9d-9d4145edffe5.png)
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/10180760/189433695-ee012588-4042-4396-8731-37e997db5bff.png">
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/10180760/189433766-8f41cf20-206d-4657-a85e-bd5bcadba28c.png">
Other pins listed test the same

**Comment by hkzlab** [comment] 2022-09-09 20:39
Hmm, I suspect the issue is just the 0x3FFFF mask in the buildWRITECommand method of src/main/java/info/hkzlab/dupal/peeper/board/dupalproto/DuPALProto.java

Alas I'll be away from the lab for quite some time with just a phone available, so can't do much debugging at the moment. But you can just try removing that mask (or just setting it to 0xFFFFFFFF) and see if it helps. I'd appreciate a PR in that case :-)

I see that you dumped the response from the board and not the actual command being sent. I suspect the command itself will contain just zeros too, but worth a double-check if you have the time.

**Comment by raymondh2** [comment] 2022-09-09 20:51
I appreciate the fast response. I'll take a look at the mask when I get back in my lab.

**Comment by hkzlab** [comment] 2022-09-09 23:39
Merged both Pars, and thanks for the help!

**Closed by hkzlab** 2022-09-09 23:39 UTC
Labels: bug
